#!/bin/bash

# Check if the distribution is Amazon Linux
if [[ $(cat /etc/os-release | grep '^ID=' | cut -d'=' -f2) == 'amzn' ]]; then
    echo "Amazon Linux detected. Installing Docker..."

    # Install Docker using sudo and yum
    sudo yum install -y docker

    # Start and enable Docker service
    sudo systemctl enable docker
    sudo systemctl start docker

else
    echo "Unsupported distribution. Docker installation aborted."
    exit 1
fi
