name: docker image 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    # - name: build the docker image
    #   run: docker build . --file docker-file --tag tasneemdabash/final-python:

    - name: build the docker image
      run: docker build . --file Dockerfile --tag tasneemdabash/final-python:${{ github.run_number }}-${{ github.sha }}

    - name: Login to Docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_PASS }} -p ${{ secrets.DOCKER_HUB_USER }}
      
    - name: Push Docker Image to Registry
      run: docker push tasneemdabash/final-python:${{ github.run_number }}-${{ github.sha }}